# Generated by Django 2.2.10 on 2021-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('explanation', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CR', 'Critical'), ('ME', 'Medium'), ('LO', 'Low')], max_length=2)),
            ],
        ),
    ]
